#Site Title, passed to the template when rendering
site-title: Markdown Tree Example Site 

#Template folder, relative to root directory of markdown-tree
template-folder: template

#Hierarchy folder, should contain tree of folders and markdown files
hierarchy-folder: content 

#Markdown extension you use for your files (md, mkd, markdown, etc.)
markdown-extension: md
